source: /docs
title: Aleksandr Maskalev
author:
  name: Aleksandr Maskalev
  email: avmaskalev@gmail.com
description: >
  Write about what I've learned and what inspires me
domain: maskalev.github.io
baseurl: ""
url: "https://maskalev.github.io"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
remote_theme: jekyll/minima
header_pages:
  - blog.md
  - til.md
  - my_projects.md
  - about.md
minima:
  skin: classic
  social_links:
   - { platform: rss, user_url: "http://127.0.0.1:4000/feed.xml" }
   - { platform: github, user_url: "https://github.com/maskalev" }
   - { platform: linkedin, user_url: "https://www.linkedin.com/in/aleksandr-maskalev" }
   - { platform: telegram, user_url: "https://t.me/clickclickclick" }
   - { platform: gmail, user_url: "mailto:avmaskalev@gmail.com" }
